### ISSUE TITLE
Outputted box-shadow property is different from input value.

### ISSUE THREAD

**Issue by rikuxs** [gucong3000/postcss-unprefix#1]
Negative value becomes positive value, and blur distance disappears.
Why does it happen?

Input code
`box-shadow: -1px -1px 1px rgba(0, 0, 0, 0.2) inset;`

Output code
`box-shadow: 1px 1px rgba(0, 0, 0, 0.2) inset;`

**Comment by gucong3000** [comment]
@rikuxs 
It is fixed,try v1.0.0 of `postcss-unprefix`
