### ISSUE TITLE
v2.0.0 Removes ::-webkit-scrollbar, v2.0.1 selector parser breaks

### ISSUE THREAD

**Issue by GeKorm** [gucong3000/postcss-unprefix#16]
Hello, 

After upgrading to >v2 this plugin removes `.class::-webkit-scrollbar` rules.  
Also, v2.1.0 throws `Error: Cannot find module 'postcss-selector-parser'`

Thank you for your work on this plugin

**Comment by gucong3000** [comment]
Fixed in v2.1.0. thanks a lot.
