### ISSUE TITLE
how can i prevent `-webkit-overflow-scrolling: touch;` from being removed when using this module

### ISSUE THREAD

**Issue by lovelyelfpop** [gucong3000/postcss-unprefix#38]
`-webkit-overflow-scrolling: touch;` is important for ios, I want to keep it from being removed. How can I do that?

**Comment by gucong3000** [comment]
Can you provide an example code of the error?

**Comment by gucong3000** [comment]
> What CSS is needed to reproduce this issue?

e.g.

```css
.foo {
  color: pink;
}
```

**Comment by gucong3000** [comment]
Now state that should not have happened, see testcaes:

input:
https://github.com/gucong3000/postcss-unprefix/blob/master/test/fixtures/supports.css#L23
output:
https://github.com/gucong3000/postcss-unprefix/blob/master/test/fixtures/supports.out.css#L15
