### ISSUE TITLE
should unprefix really remove ALL prefixes?

### ISSUE THREAD

**Issue by asinning** [gucong3000/postcss-unprefix#51]
With one exception, unprefix does exactly what I need.  We distribute ePub titles to school libraries in our own e-reader.  The files which we get from publishers often include declarations for specific browsers, but are missing the more general prefix-less declaration.  So, we run the css through unprefix and then autoprefixer, just like the documentation in the readme.

The problem has to do with the declaration "-webkit-background-clip: text".  autoprefixer does not recognize that "background-clip: text" needs to be prefixed.

Should autoprefixer be doing "background-clip: text" -> "-webkit-background-clip: text", or should unprefix leave the prefix in place?

How would I create an exception to prevent unprefix from touching certain rules?

**Comment by gucong3000** [comment]
> autoprefixer does not recognize that "background-clip: text" needs to be prefixed.

Maybe there's something wrong with your configuration, here is [a test case in `autoprefixer` for `background-clip`](https://github.com/postcss/autoprefixer/blob/master/test/cases/background-clip.out.css)

**Comment by gucong3000** [comment]
> How would I create an exception to prevent unprefix from touching certain rules?
I think it can be [implemented in stylelint](https://github.com/stylelint/stylelint/pull/2565).

**Comment by asinning** [comment]
>>How would I create an exception to prevent unprefix from touching certain rules?

>I think it can be implemented in stylelint.

Could you please be a bit more specific?  Where would I use stylelint?  Before, after, instead of, or as an extension of unprefix?

**Comment by gucong3000** [comment]
There's something wrong with your [browserslist configuration](https://github.com/ai/browserslist) for autoprefixer.
This example works fine: 
```json
{
  "browserslist": [
    "android >= 2"
  ],
  "name": "test",
  "version": "0.0.0",
  "main": "index.js",
  "scripts": {
    "test": "postcss in.css --use postcss-unprefix --use autoprefixer -o out.css"
  },
  "devDependencies": {
    "autoprefixer": "^7.2.5",
    "postcss-cli": "^4.1.1",
    "postcss-unprefix": "^2.1.1"
  }
}
```

in.css
```css
a {
	-webkit-background-clip: text
}
```
out.css
```css
a {
	-webkit-background-clip: text;
	        background-clip: text
}
/*# sourceMappingURL=xxxxxxxx */
```

**Comment by gucong3000** [comment]
Autoprefixer will **not** add all prefixes unless the browser in you configure requires.

**Comment by asinning** [comment]
Thanks!  This is exactly what I needed!
